### PR TITLE
expand working directory before cloning into it

### PR DESCRIPTION
**Pull request by jalalawqati**
Using `$CIRCLE_WORKING_DIRECTORY` directly would clone into a literal `~/project`, without expanding the tilde (~) first. This was working before since the shallow checkout command was cloning directly into a variable passed by the calling workflow.

Since we rely on `$CIRCLE_WORKING_DIRECTORY` directly now instead, the shallow checkout was cloning into `~/~/project` instead of `~/project`, since `$CIRCLE_WORKING_DIRECTORY` was literally pointing to `~/project`, and not the expanded path

### CODE REVIEW

**Review by mathaeus — APPROVED** [review]
Haven't we been using this checkout shallow command before on iOS already? Or Android?
Just trying to understand why it has not been working as expected now.

p.s. Maybe add a comment?

**Comment by jalalawqati** [comment]
@mathaeus I've updated the description 👍

**Comment by mathaeus** [comment]
Push push? :) @jalalawqati

**Comment by mathaeus** [comment]
Ah you updated the PR description... was a misunderstanding

**Pull request merged**
